"""create table PriceСrypto

Revision ID: eac1c6f0a3b7
Revises: 
Create Date: 2025-02-20 18:11:54.157478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac1c6f0a3b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('max_price', sa.Numeric(), nullable=False),
    sa.Column('min_price', sa.Numeric(), nullable=False),
    sa.Column('difference', sa.Numeric(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('date_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_crypto_date_at'), 'price_crypto', ['date_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_crypto_date_at'), table_name='price_crypto')
    op.drop_table('price_crypto')
    # ### end Alembic commands ###
